version: '3.8'

services:
  yii2-app:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG:-latest}
    environment:
      - YII_ENV=${APP_ENV:-prod}
      - DB_DSN=${DB_DSN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    deploy:
      replicas: ${REPLICAS:-2}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - yii2-network

networks:
  yii2-network:
    driver: overlay
    attachable: true
